database:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'toor'
  database: 'inpulse'
  pool_size: 50  

api:
  base_url: 'http://192.168.10.174:1237'
  prtg_url: 'https://nms.bcomintelsat.com/api/inpulse.json'
  apitoken: 'AIF34EXINKSKOB3Y4BQUQGOZYJQFRNB6OZFSJM2MJI======'
  max_concurrent_device_info_requests: 10 

logging:
  level: 'INFO'

data:
  base_directory: 'C:/Users/GabrielGhossoub/Desktop/DataNew2'

max_concurrent_sensors: 5